### ISSUE TITLE
Provisioning of ESP32 Camera

### ISSUE THREAD

**Issue by KunjalRupala** [aws-quickstart/quickstart-onica-connected-camera#11]
Hey,
I wanted to know if its possible to provision an ESP32 AIThinker Camera Module?
I know you have given a list of companies which provide this service in Appendix A of the guide but still I wanted to know if any other camera will work?

**Comment by sshvans** [comment]
@KunjalRupala The listed cameras in the Quick Starts are identified as the supported cameras. Other cameras may or may not work.

**Comment by KunjalRupala** [comment]
Hey @sshvans,
Can you tell me a method via which I can provision my camera and make a supportbale one?
