### ISSUE TITLE
Provisioning new stack via Cloudformation Fails

### ISSUE THREAD

**Issue by akki-io** [aws-quickstart/quickstart-onica-connected-camera#12]
We are trying to provision a new stack using the CF template provided. But it fails to provision the Lamba Functions.

Here are the errors we are getting

![image](https://user-images.githubusercontent.com/34255218/71877591-8682dd00-30f7-11ea-8a27-4629df5f9e5b.png)

Any ideas/help on how we can fix these?

**Comment by davmayd** [comment]
The Quick Start was using the nodejs runtime 8.1, which is no longer supported. The runtime has since been updated to 10.x and the template should deploy successfully.
